### ISSUE TITLE
Unhandled exception: Immediately after starting up

### ISSUE THREAD

**Issue by Xayrlen** [Fris0uman/CDDA-Game-Launcher#17]
* Description: whenever I try to launch a launcher this happens.
* Version: 1.5.8
* OS: Windows-10-10.0.19041-SP0 (64-bit)
* Type: `<class 'IndexError'>`
* Value: list index out of range
* Traceback:
```
  File "cddagl\ui\views\main.py", line 1368, in showEvent
  File "cddagl\ui\views\main.py", line 3129, in refresh_builds
  File "cddagl\ui\views\main.py", line 3181, in refresh_changelog

```

**Comment by TpKek** [comment]
Can confirm I'm having the same issue:
![image](https://user-images.githubusercontent.com/92753848/170839053-b252c53e-7474-4899-8fff-cb5de82a11f7.png)

**Comment by ThePainkiller** [comment]
We all are having the same one it seems.

![image](https://user-images.githubusercontent.com/1294508/170870331-63ed62ff-40f9-4b5b-8f20-cf36240d2c8a.png)
