### ISSUE TITLE
"api-ms-win-core-path-l1-1-1.dll is missing"  (+fix)

### ISSUE THREAD

**Issue by BlumiMilch** [Fris0uman/CDDA-Game-Launcher#22]
Launcher Version: 1.6.0
OS: Windows 7 64-Bit

The launcher did not start and I got a message box that showed "api-ms-win-core-path-l1-1-1.ddl is missing"

Fix:
I followed the instructions in https://github.com/nalexandru/api-ms-win-core-path-HACK and the launcher is running now

**Comment by Fris0uman** [comment]
Can you re-download the lastest release https://github.com/Fris0uman/CDDA-Game-Launcher/releases/tag/v1.6.0 try again an see if it still gives you an error? I chnaged le exe to be compatible with win7

**Comment by BlumiMilch** [comment]
I reverted the fix by renaming "api-ms-win-core-path-l1-1-1.dll" in C:\Windows\System32\ and C:\Windows\SysWOW64\ and restarted my computer. After that I started the new Launcher 1.6.0 and it is working, thanks!
