### ISSUE TITLE
Unhandled exception: Crashes, Possibly due to non-default game directory

### ISSUE THREAD

**Issue by Travia21** [Fris0uman/CDDA-Game-Launcher#27]
* Description: I just updated the launcher and it failed to start. It does rollback successfully. My game directory is not in C:
* Version: 1.6.1
* OS: Windows-10-10.0.19041-SP0 (64-bit)
* Type: `<class 'TypeError'>`
* Value: expected str, bytes or os.PathLike object, not NoneType
* Traceback:
```
  File "cddagl\ui\views\main.py", line 281, in showEvent
  File "cddagl\ui\views\main.py", line 745, in game_directory_changed
  File "cddagl\ui\views\main.py", line 1020, in update_saves
  File "ntpath.py", line 78, in join

```

**Comment by Xayrlen** [comment]
Exactly the same problem here, can confirm.

**Comment by Fris0uman** [comment]
What did it show in the `Session` entry?

**Comment by Fris0uman** [comment]
Can you retry downloading v1.6.1 and tell me if it fixes the issue? (I've uploaded the build from #29 but I'm not sure it fixes the issue since I don't know how to reproduce it locally)

**Comment by Travia21** [comment]
I just tried an automatic update and it failed with the same error message.

**Comment by Fris0uman** [comment]
And now? What happens if you try again?

**Comment by Travia21** [comment]
Wunderbar! That did it.
