### ISSUE TITLE
Launcher Binary Doesn't Update

### ISSUE THREAD

**Issue by Travia21** [Fris0uman/CDDA-Game-Launcher#30]
**Describe the bug**
The launcher doesn't update the binary executable on disk. It puts a new launcher.exe in C:\Users\username\AppData\Local\Temp\...

**To Reproduce**
1. Open launcher.exe version 1.6.0
2. Update when prompted
3. Check the version number in Help, see it's 1.6.1
4. Close the launcher
5. Open the same launcher.exe
6. You are prompted to update again

**Expected behavior**
The binary launcher.exe on disk should get replaced with the new version.

**Screenshots**
![image](https://user-images.githubusercontent.com/3219079/180608362-6c2c654a-0a19-440c-882f-b1238421b465.png)
![image](https://user-images.githubusercontent.com/3219079/180608436-0990152f-2775-441b-aed5-70b16b776907.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
My launcher.exe is not on my C: drive. Every time I update, a new "cdda..." folder is added to C:\Users\Username\AppData\Local\Temp.

**Comment by Fris0uman** [comment]
Can confirm, also apparently this has been the behaviour since version1.5.8. It will probably take me some time to fix

**Comment by Travia21** [comment]
The workaround is to move the exe from temp to where it needs to go.
