### ISSUE TITLE
Third party mods are not retained when updating

### ISSUE THREAD

**Issue by Factoriac9** [Fris0uman/CDDA-Game-Launcher#39]
**Describe the bug**
Third party mods are not retained when updating the game via the launcher.
According to "How does the launcher update my game?" in the FAQ these should be copied from the last version when updating.

**To Reproduce**
1. Install game through the latest version of the launcher
2. Install a third party mod (i.e. Arcana and Magic Items) by dropping it into the data\mods directory
4. update the game through the launcher
5. the third party mod is in the mods directory of the backup of the previous version, but is not in the mods directory of the new version. Third party mods will need to be manually copied from the previous version to successfully load a save including them.

**Expected behavior**
Third party mods should be copied from the previous version after updating

**Desktop:**
 - OS: Windows 10

**Additional context**
This could be working as intended, but the README should probably be updated to correctly indicate this if that is the case.

**Comment by Fris0uman** [comment]
https://github.com/Fris0uman/CDDA-Game-Launcher/pull/19 this should have fixed that already

**Comment by Factoriac9** [comment]
Appreciate you looking at this... I just tried backing up & deleting my game, re-downloading version 1.6.3 of the launcher and doing a brand new install of cdda. I then put the arcana mod into the cdda mods directory and created a new world with the mod. When I quit the game and force update through the launcher, the mod is definitely removed from the mods directory but is in the mods directory of the previous backup. Maybe something has got broken again since that fix?
