### ISSUE TITLE
Backup's don't seem to be working?

### ISSUE THREAD

**Issue by Ryan7251** [Fris0uman/CDDA-Game-Launcher#42]
I have tried to make a few backups but every time i do the launcher fails to make the backup save it says saves backups completed made it but nothing shows up on the list.

**Comment by LithiumMirnuriX** [comment]
ditto. sometime failed, crashed and corrupted during backup...

**Comment by rightdroid** [comment]
Same here. Backing up creates empty zips in the `save_backups` folder. Backups available shows nothing. So currently have to manually backup saves.
