### ISSUE TITLE
Latest builds are unavailable

### ISSUE THREAD

**Issue by RedMisao** [Fris0uman/CDDA-Game-Launcher#67]
**Describe the bug**
Since 2024-02-28-1558, all builds are unavailable, and can't be downloaded

**To Reproduce**
1. Open the launcher
2. Check the "Available builds" tab, see the builds are grayed out
Clicking on "refresh" does nothing

**Expected behavior**
Be able to download the latest experimentals

**Screenshots**

![8](https://github.com/Fris0uman/CDDA-Game-Launcher/assets/95231551/4f22fb6a-0b29-49e7-b9a1-b060dd681e85)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 21H2

**Additional context**

**Comment by NafenX** [comment]
Same here, I thought it was because I had ignored the launcher update to fix one of the soundpacks or something, but once I updated the launcher I still couldn't update the game

**Comment by jeffnonumber** [comment]
Same here, but switching build type from "mscv" to "other" seems to fix it, no idea why

![image](https://github.com/Fris0uman/CDDA-Game-Launcher/assets/8654251/f9cd0dc2-eacf-41e6-bfc3-e647d9af3709)

**Comment by Fris0uman** [comment]
Unrelated to the launcher, the msvc build is currently busted, chose the `other` build

**Comment by RedBloodCat** [comment]
Its been fixed now btw

**Comment by NafenX** [comment]
![image](https://github.com/Fris0uman/CDDA-Game-Launcher/assets/28961736/3f706c9c-d33a-477d-a6c5-d6da54cf8b31)

I dunno if this is just related to the latest experimental but I'm still seeing build unavailable even on 'other' build type 😅 Not a huge deal but just never seen build unavailable before

**Comment by RedBloodCat** [comment]
![image](https://github.com/Fris0uman/CDDA-Game-Launcher/assets/49415411/6064b997-1404-4e8b-83ff-f97a1dbe29ca)
Seems fine now, i know it might take some time for it to compile so it might be that you where just to fast

**Comment by jeffnonumber** [comment]
I dunno, it still looks like something is going on
![image](https://github.com/Fris0uman/CDDA-Game-Launcher/assets/8654251/805a67af-f0ff-42ea-a9d4-ee60472201dd)

**Comment by NafenX** [comment]
![image](https://github.com/Fris0uman/CDDA-Game-Launcher/assets/28961736/07313610-eaa8-4f65-8a2b-c9655bcb7004)
![image](https://github.com/Fris0uman/CDDA-Game-Launcher/assets/28961736/6a1d83cc-565f-491b-adb8-ef0ee21c8e5e)
![image](https://github.com/Fris0uman/CDDA-Game-Launcher/assets/28961736/8666e4e7-867d-444f-b9f0-25bef84c8303)

Now the newest build is not even showing in list (even as build unavailable) on either build type, though I see new things today in changelog 🤔

**Comment by Fris0uman** [comment]
Again not a problem with the launcher, there literally isn't any new builds https://github.com/CleverRaven/Cataclysm-DDA/releases 
![image](https://github.com/Fris0uman/CDDA-Game-Launcher/assets/41293484/58cb7eed-8594-466b-8a4d-5e1f0d362316)

**Comment by NafenX** [comment]
Apologies if I'm still somehow missing something or misunderstanding, but the two unavailable ones here in the launcher are currently on the releases page for CDDA. I don't know if I'm doing something wrong or if it's just slow to become available in the launcher

![image](https://github.com/Fris0uman/CDDA-Game-Launcher/assets/28961736/996ecd2c-9c52-4f41-8896-9857f11901b0)

**Comment by Fris0uman** [comment]
In 9 cases out 10 `build unavailable` means the build didn't work right and there's nothing that can be done about it on the launcher side
