### ISSUE TITLE
[Errno 2]

### ISSUE THREAD

**Issue by mechabattra** [Fris0uman/CDDA-Game-Launcher#68]
**Describe the bug**
When attempting to update the experimental version of CDDA via the launcher I received the following error message: [Errno 2] No such file or directory: 'C:\\Users\\[UserName]\\AppData\\Local\\Temp\\xddagl16w_8hlx\\'. On each subsequent click of the 'Update game' button, a different string of letters comes up, see attached screenshot for another example. 

**To Reproduce**
Might not be applicable. This may be something on my end.

**Expected behavior**
I would expect the experimental update to download via the launcher as per usual. 

**Screenshots**
![Screenshot 2024-03-06 205031](https://github.com/Fris0uman/CDDA-Game-Launcher/assets/162494254/f12a0539-41a9-45ad-8d63-2d033d401394)

**Desktop (please complete the following information):**
 - OS: Windows.
 - Version: 11

**Additional context**
I had updated the launcher to v1.7.1 when it came out. I also updated the experimental branch in the following days with no issue. It is only today (06/03) that this error message started appearing. I attempted to resolve it by reinstalling the launcher and game: this didn't work. I should also note that **downloading the stable branch does not cause this error to appear**. I can download that just fine. Additionally, I have already tried whitelisting the app with my antivirus.

**Comment by mechabattra** [comment]
Hello,
I managed to get it to download by selecting 'other' as the build type opposed to 'msvc'.

**Comment by RedBloodCat** [comment]
Not a problem with the launcher, mcvs build don't work for a few days. It has been fixed now

**Comment by Fris0uman** [comment]
After some investigation this will only happen when all builds are unavailable, which should be fixable on the user end by switching the build type. I'll see If can make that more clear to users, like maybe by disabling the update button if there are literally no build no download
