### ISSUE TITLE
Add this new soundpack to the repository

### ISSUE THREAD

**Issue by Sorrow-Scarlet** [Fris0uman/CDDA-Game-Launcher#72]
* Name: [Otopack+ModsUpdates]
* Url: [Enter the Url where we can find the soundpack](https://github.com/Kenan2000/Otopack-Mods-Updates/releases)
* Author: [Survival_Man+Kenan2000]
* Homepage: (https://github.com/Kenan2000/Otopack-Mods-Updates)
* Soundpack not found in version: 1.7.1

**Comment by Fris0uman** [comment]
ths is not new, and it's not in the launcher on purpose, see https://github.com/Fris0uman/CDDA-Game-Launcher/pull/62
