### ISSUE TITLE
3rd party mod not retained on update

### ISSUE THREAD

**Issue by AdamBrezik** [Fris0uman/CDDA-Game-Launcher#89]
Hi,
    I'm using UDP_BN_FAKE_SNOW. It gets removed on each update. It's not a big deal to run a script to copy it back, but it still seems to me like it'd be a good thing to have a functionality that would let user decide whether or not does the mod get removed at least. If this is a FR, please let me know, but I saw a similar issue closed, so I opened it as an issue.

**Comment by Fris0uman** [comment]
BN is a different game from dda. Dda 3rd party mods are not removed as far as I can tell

**Comment by AdamBrezik** [comment]
The mod is present in the game and functioning without issues. The only issue is that the launcher keeps removing it. What I suggest is to give user options to mitigate this unwanted behavior whether it's by design or not because either way it's a nuisance.

**Comment by Fris0uman** [comment]
Just tested it: Made a new mod, put it in data/mods ,update with the launcher, check if the mod it still in data/mods and it is

**Comment by AdamBrezik** [comment]
I changed ident to id and I added obsolete as false.

One of these obviously helped, so we can close this if you want.

**Comment by Fris0uman** [comment]
ident is a BN thing, because you're using a mod made for a different game.

**Comment by AdamBrezik** [comment]
...works nonetheless.
