### ISSUE TITLE
cataclysm-tiles.exe, cataclysm-tiles.pdb and json_formatter.exe freshly downloaded contain mentions of previous game path

### ISSUE THREAD

**Issue by AideeAmei** [Fris0uman/CDDA-Game-Launcher#93]
**Describe the bug**
I moved the game and the launcher to another drive on Windows recently. Everything seemed to be fine.
After the last update I'm getting some error in-game that may not be related to this and doesn't seem to have any in-game influence (or at least it's something minor and I haven't noticed yet) but what stroke me is that the error is mentioning a file in the previous path:

 DEBUG    : Error parsing tripoint coordinate in item::get_var: Stray characters after integer in '0)'

 FUNCTION : operator ()
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\item.cpp
 LINE     : 1913
 VERSION  : 9ac7d05

The current path is C:\Games\cdda\game\fresh (I was curious so I downloaded a fresh instance to a new folder, my normal is C:\Games\cdda\game\latest). What is interesting is that this happens in a freshly downloaded latest version so I'm trying to figure out whether this is something related to the launcher itself. I scoured registry for any mention of cataclysm or cdda but the stuff I found seemed to be just random app caches like winrar etc. but I removed almost everything (nothing seemed important).

When I ransack the fresh game install I see this:
![image](https://github.com/user-attachments/assets/5068ea08-9a88-4aa9-9f5d-3f6abec5748a)

**To Reproduce**
1. In launcher, install the game to a fresh folder
2. Ransack the folder for "D:\a\Cataclysm-DDA"

**Expected behavior**
I don't know what to expect and why, I suspect this is saved somewhere in the registry but wasn't able to find it.

**Desktop (please complete the following information):**
 - OS: Windows
 - 10 Pro 64-bit 22H2 19045.5131

**Additional context:**
When I download CDDA separately and I search the files for the string, I get no matches.

**Comment by Fris0uman** [comment]
The error message is unrelated to the launcher, and the rest is not an actual issue

**Comment by AideeAmei** [comment]
It is curious at best, that the files would already have this path in them and I'd have saved in the same odd path utterly cluelessly. 

I'm gonna try to reproduce this on another machine.


Anyway I'm getting multiple in-game errors now and all point to this old path. This started happening roughly a week ago and I moved CDDA to C: at least 3 weeks ago.

I take the comment about the origin of the path is an estimation, not confirmed with a proof of sorts.

**Comment by AideeAmei** [comment]
> The error message is unrelated to the launcher, and the rest is not an actual issue

How can something that's happening only with launcher installation not be related to the launcher?

**Comment by RenechCDDA** [comment]
> I'm gonna try to reproduce this on another machine.
> 
> Anyway I'm getting multiple in-game errors now (I'm not saying they're related) and all point to this old path. This started happening roughly a week ago and I moved CDDA to C: at least 3 weeks ago.
> 
> Let's say it's not an issue, but it still doesn't make sense and it shouldn't happen. So if anyone has a clue why this is happening, it'd be more than welcome.

As mentioned, the filepath shown is the directory of the source files when the game was compiled. By github's machines.

Github's machines can use whatever filepath they want. It's not relevant to you.

>How can something that's happening only with launcher installation not be related to the launcher?

Try to load your save without the launcher, you will find it has the exact same error.
